# <<<<<<< HEAD
# # Generated by Django 4.2.4 on 2023-09-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=122)),
                ('Password', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=122)),
                ('Password', models.CharField(max_length=122)),
                ('Confirm_Password', models.CharField(max_length=122)),
            ],
        ),
    ]
=======
# Generated by Django 4.2.4 on 2023-09-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=122)),
                ('Password', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=122)),
                ('Password', models.CharField(max_length=122)),
                ('Confirm_Password', models.CharField(max_length=122)),
            ],
        ),
    ]
>>>>>>> ec1b04c51aa47d53cc7f7a79635d1ae8d26bbf61
